### ISSUE TITLE
News-Selection/Data-Source for tagesschau telegram bot 

### ISSUE THREAD

**Issue by atticus-sullivan** [AndreasFischer1985/tagesschau-api#11]
Hi,
I'm currently building a chat bot (no worries, just a hobby project, no commercial use) which should periodically send the news just like the telegram [tagesschau bot/channel](https://t.me/ARD_tagesschau_Bot) (but not on telegram). For now, I'm still searching where to get these information. I already checked out the `api2`, documented in this repo, but as far as I checked it, this does not seem to be the data-source for the telegram bot (the texts do not really match).

I'm not sure if you're somehow affiliated with the tagesschau, so maybe you know something about the data-source of the official tagesschau telegram bot/channel (up to now I wasn't able to find any source code for it).

EDIT: Just found https://fragdenstaat.de/anfrage/quellcode-des-telegram-bots-der-tagesschau/ but the request is still (and most probably will stay) unanswered.

**Comment by plueschpruem** [comment]
I don't know it for a fact, but if it is the official channel of Tagesschau, then they most likely have a team just for re-curating their own material for that specific outlet. After all they have a 8+ Bio. EUR budget to burn through each year (for all the federal media, news is just a small fraction of that)…

**Comment by atticus-sullivan** [comment]
Hm, seems like this is the case. Coming from the fact that the messages from the telegram bot are always sent slightly at a different time, the most probable reason is that there are humans curating the messages before sending. And I think the text also is a bit different (tailored for the short messenger message) from the text obtained from the api.

With the breaking news from the headerapp api-endpoint it seems to be the same.


A bit sad that there is no API-access to the curated messages.
