### ISSUE TITLE
Tagesschau API has changed dramatically

### ISSUE THREAD

**Issue by plueschpruem** [AndreasFischer1985/tagesschau-api#12]
https://www.tagesschau.de/api2u is dead now.
https://www.tagesschau.de/api2u/news still works, while most other API endpoints now either throw an error or display a "not found / technical difficulties" page.

**Comment by beta-tester** [comment]
for testing i used https://tagesschau.api.bund.dev/ to execute API:
- https://www.tagesschau.de/api2/
  response 404 (ERROR)
- https://www.tagesschau.de/api2/homepage/
  response 200 (OK)
- https://www.tagesschau.de/api2/news/?regions=1&ressort=ausland
  response 200 (OK)
- https://www.tagesschau.de/api2/newsfeed-101~_date-220228.json
  response 404 (ERROR)
- https://www.tagesschau.de/api2/search/?searchText=Ukraine&pageSize=0&resultPage=2
  response 404 (ERROR)
- https://www.tagesschau.de/api2/ausland/
  response 404 (ERROR)
- https://www.tagesschau.de/api2/channels/
  response 200 (OK)
- https://www.tagesschau.de/api2/multimedia/
  response 404 (ERROR)

a lot of API stuff is broken

**Comment by AndreasFischer1985** [comment]
Thank you very much, I just deleted the broken endpoints. 

There also seems to be a new endpoint available (https://www.tagesschau.de/json/headerapp) and some POST-requests to https://zagent29.h-cdn.com & 
https://perr.h-cdn.com but these are not documented yet.

**Comment by beta-tester** [comment]
@AndreasFischer1985, thank you.

but i am a little bit confused.
the BundesAPI uses a fork of your repository for Tagesschau API.
the nameing _**BundesAPI**_ suggests that there is the goverment behind this API. and should be open and freefor the public (at least for locations inside germany)

https://bund.dev/apis/
https://github.com/bundesAPI

how is it possible that the Tagesschau API has changed but nobody has a documentation of the new API?

why was it changed and are there other endpoints available to archive the same functionality as befor?
e.g. there is a Kodi addon that needs to get multimedia or search response.

so it is not you who made the Tagesschau API endpoints... who is doing it?

**Comment by vitusson** [comment]
The ARD is the ARD and not a  Bundesbehörde.  There is no government behind the API

**Comment by beta-tester** [comment]
ok, i thought there is something like a law to open-data or a "mediengesetz".
then i expected too much.

**Comment by mundanevision20** [comment]
this change breaks the **search** feature in the official app for me. So I checked the network requests and they forward all search requests (e.g. `https://www.tagesschau.de/api2u/search/?searchText=&pageSize=25&resultPage=0`) to the `/api2u/suche` endpoint which returns a 404 error.
All of this feels like a failed migration. There's also `https://www.tagesschau.de/app/config/app3-versions.json` which also returns a 404 error. To sum it up the communction between backend and frontend is just completely messed up.

Given that the change to most endpoints see e.g. `https://www.tagesschau.de/api2u/news/?ressort=wirtschaft` is just the single character `u` it might be that the wanted to break any inofficial third party integration. Or it's just simply a typo by someone running a search&replace on their code.

I also stumpled across `https://www.tagesschau.de/api2u/commuteplaylist` which has not been named before. This endpoint simply returns a list of audio news (see 'Audio-Nachrichten' in the app)

The endpoint `https://www.tagesschau.de/api2u/newStoriesCount` can be used to quickly check for updates in all resorts.

The **recommendations** algorithm serves results at `https://storage.googleapis.com/tagesschauatifosrecommendation-prod/recommendations/SOPHORA_ID.json` (insert `sophoraId` of news item here).

**Comment by AndreasFischer1985** [comment]
> @AndreasFischer1985, thank you.
> 
> but i am a little bit confused. the BundesAPI uses a fork of your repository for Tagesschau API. the nameing _**BundesAPI**_ suggests that there is the goverment behind this API. and should be open and freefor the public (at least for locations inside germany)
> 
> https://bund.dev/apis/ https://github.com/bundesAPI
> 
> how is it possible that the Tagesschau API has changed but nobody has a documentation of the new API?
> 
> why was it changed and are there other endpoints available to archive the same functionality as befor? e.g. there is a Kodi addon that needs to get multimedia or search response.
> 
> so it is not you who made the Tagesschau API endpoints... who is doing it?

The team at the civil society initiative bund.dev documents APIs in the bundesAPI repo (voluntarily), 
but is not responsible for developing the APIs.

**Comment by beta-tester** [comment]
> All of this feels like a failed migration. 

is somebody using the Tagesschau-App? is this App using the same tagesschau API and is it broken as well?

EDIT: the app was updated recently. if somebody usinf the app, maybe you can sniff the new API traffic.
![tagesschau-app](https://user-images.githubusercontent.com/4750719/235314777-e3e14a4b-66d2-4ff8-a833-44ba93a70cd9.png)

**Comment by plueschpruem** [comment]
Yes, last week the app completely stopped showing images.
After the updates it worked again.
Kinda botchy this rollout…

**Comment by vitusson** [comment]
>All of this feels like a failed migration. 

Yep.
Update of Tagessschau-App on 25.04.
https://www.tagesschau.de/app

**Comment by beta-tester** [comment]
does the Tagesschau App show "Tagesschau 20Uhr" entries from more than only the most recent day?
 in the Kodi addon the functionallity is gone to view "Tagesschau 20Uhr" from the past 7 (or so) days. i think it is because the API endpoint to list multimedia files is gond. but if the "Tagesschau App" is still able dor list files from the last few days, there must be another way to rebuild that functionality.

**Comment by beta-tester** [comment]
the search API endpoint seems to be back again.
i get search results instead of an erro now:
e.g.: https://www.tagesschau.de/api2u/search/?searchText=Tagesschau+Geb%C3%A4rdensprache
or https://www.tagesschau.de/api2u/search/?searchText=Tagesthemen

**Comment by beta-tester** [comment]
@AndreasFischer1985 can you please bring back the search endpoint to the page https://tagesschau.api.bund.dev/
