### ISSUE TITLE
activate github-pages

### ISSUE THREAD

**Issue by t-huyeng** [AndreasFischer1985/tagesschau-api#2]
Proberly something more for https://github.com/bundesAPI/tagesschau-api, but since it is a fork, I can not open an Issue there. 

Github Pages are not activated, so https://tagesschau.api.bund.dev/ does not currently work (unsure if it is already in the terraform repo). 

Is this on purpose @AndreasFischer1985?

**Comment by AndreasFischer1985** [comment]
I just activated the GitHub Pages site for this and some other repos of mine (e.g., https://bundesapi.github.io/tagesschau-api/index.html). Adding it in the terraform repo is still on my to do list.
