### ISSUE TITLE
Manche Attribute des News-Objekt sind are optional

### ISSUE THREAD

**Issue by septatrix** [AndreasFischer1985/tagesschau-api#5]
Z.b. der Artikel von heute mit Titel "Und so wird das Wetter" hat keine ids und auch keine `klein1x1` Variante der Bilder.

**Comment by AndreasFischer1985** [comment]
Vielen Dank für den Hinweis. Ich werde heute versuchen, die openapi.yaml entsprechend anzupassen bzw. bei der HomepageResponse diejenigen Elemente als "required" auszuweisen, die beim Wetter ebenso wie bei den übrigen news Verwendung finden (by default sollten eigentlich alle Elemente als optional gelten). Sollte es weitere Unterschiede geben, gerne melden oder direkt via Pull Request beitragen.

**Comment by septatrix** [comment]
Ah okay, dafür kenne ich mich dann nicht genug mit openapi aus und dachte sie wären per Default required, danke. Ich werde mal ein wenig mit der API experimentieren und mich melden falls ich auf sonstige Probleme stoße.
